name: Deploy to EC2

on:
  push:
    branches: [develop, deploy-to-ec2]
  pull_request:
    branches: [develop, deploy-to-ec2]

permissions:
  packages: write
  contents: read

env:
  DOMAIN: citrineos.vertix.digital

jobs:
  build-and-push-citrineos-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm run install-all --frozen-lockfile
        
      - name: Build applications
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Server/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/bevolv/citrineos-core/api:latest
            ghcr.io/bevolv/citrineos-core/api:${{ github.sha }}
          build-args: |
            DOMAIN=citrineos.vertix.digital
            

  build-and-push-everest-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm run install-all --frozen-lockfile
        
      - name: Build applications
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./Server/everest
          file: ./Server/everest/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/bevolv/citrineos-core/everest:latest
            ghcr.io/bevolv/citrineos-core/everest:${{ github.sha }}
          build-args: |
            DOMAIN=citrineos.vertix.digital
            EVEREST_IMAGE_TAG=0.0.23
            EVEREST_TARGET_URL=wss://ws.${DOMAIN}/cp001
            OCPP_VERSION=two
            
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-citrineos-image
      - build-and-push-everest-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Pull latest image
      uses: appleboy/ssh-action@master
      with:
        host: citrineos.vertix.digital
        username: deploy
        key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        script: |
          docker pull ghcr.io/bevolv/citrineos-core/api:${{ github.sha }}
          docker pull ghcr.io/bevolv/citrineos-core/everest:${{ github.sha }}

    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
        echo "DOMAIN=citrineos.vertix.digital" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_HOST=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_HOST }}" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_PORT=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_PORT }}" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_NAME=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_NAME }}" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_DIALECT=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_DIALECT }}" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_USERNAME=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_USERNAME }}" >> ./envfile
        echo "BOOTSTRAP_CITRINEOS_DATABASE_PASSWORD=${{ secrets.BOOTSTRAP_CITRINEOS_DATABASE_PASSWORD }}" >> ./envfile
        echo "EVEREST_IMAGE_TAG=0.0.23" >> ./envfile
        echo "EVEREST_TARGET_URL=wss://ws.${DOMAIN}/cp001" >> ./envfile
        echo "OCPP_VERSION=two" >> ./envfile
        echo "CITRINEOS_API_KEY=${{ secrets.CITRINEOS_API_KEY }}" >> ./envfile
        echo "CITRINEOS_SECRET_KEY=${{ secrets.CITRINEOS_SECRET_KEY }}" >> ./envfile
        echo "HASURA_GRAPHQL_AUTH_HOOK=${{ vars.HASURA_GRAPHQL_AUTH_HOOK }}" >> ./envfile
        echo "HASURA_GRAPHQL_ADMIN_SECRET=${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}" >> ./envfile

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: citrine-stack
        file: docker-stack.yaml
        host: citrineos.vertix.digital
        user: deploy
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile
        registry_host: ghcr.io
        registry_user: ${{ github.actor }}
        registry_pass: ${{ secrets.GITHUB_TOKEN }}
        registry_auth: true
        mode: swarm
        detach: true
        resolve_image: always
